# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#on:
#  schedule:
#    - cron: '1 * * * *'

name: Python application

on:
  schedule:
    - cron: '1 1 1 1 *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bs4
        pip install lxml      
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run scrap
      run: |        
        python3 ScrapBisonFute.py
        ls
    - name: Push
      run: |
        git config --global user.email "benoit.gaudou@gmail.com"
        git config --global user.name "benoitgaudou"
        git config --global push.default simple
        git status
        git remote rm origin
        git remote add origin https://benoitgaudou:$GH_token_public_repo@github.com/benoitgaudou/scrap-BisonFute.git
        echo "====================================="
        git add Data/*/*/*.xml
        git status
        echo "====================================="        
        git commit -m "new data"
        git status
        echo "====================================="        
        git push origin HEAD:main

